### PR TITLE
Adds access to all jobs.

### PR DESCRIPTION
**Pull request by AnonymousHybi**
Basically what the title says, Kona asked and I've got some spare time on me to help.

Kinda done it the lazy way, would've made it another config option but im laaaazy

### CODE REVIEW

**Comment by Jakksergal** [comment]
Since we don't have TravisCI or any other merge helper, we're going to have to manually input changelogs for large releases to avoid conflicts with PRs. I can't merge this with the changelog edits. I'm going to inquire with VOREstation about how they implimented their maintenance access and follow suit.

**Comment by AnonymousHybi** [comment]
Alrighty. :P I'll just close this PR.

**Comment by AnonymousHybi** [comment]
Also I'm unsure about how to do changelogs to the point where conflicts wont happen, i guess just making a .yml ready for when the server gets the update.

**Comment by AnonymousHybi** [comment]
Then the server just uses the make changelog tool on their end.

**Pull request closed without merging**
