### PR TITLE
Buff flying

### PR DESCRIPTION
**Pull request by lbnesquik**
- Winged flight now cost 3 points.
- You now have access to Flight Agility which behaves like teshari agility, allowing you to pass over tables and such.
- 1 special flight emote was added. Airflip. Only works when in the air.

Original PR text below:
- Flying now takes half the nutrition per tick or per tile flown.
- You can now fly off the ground with more food in yourself.
- Hover costs less nutrition to trigger.

I was considering lowering or outright damage received when hitting things such as windows or tables. Thoughts?

### CODE REVIEW

**Comment by KasparoVy** [comment]
Hell yeah, hopefully flight can make a bit more sense.

Here's my (old and abandoned) attempt at sorting this myself that I never got around to PRing upstream. Created a pull on my own master for easier review https://github.com/KasparoVy/VOREStation/pull/1
Hopefully it can provide some ideas.

It includes changes such as:
- Dynamic calculation of nutrition cost based on weight & nutrition. I may have been having issues but at this point I can't recall what they were or if I fixed them. >SEE BOTTOM
- Not slipping on floor-bound items while flying.
- Not being affected by glass shards on the ground while flying.
- Improved flight animation.
- Not being 'submerged' if over water while flying.
- Flight over railings & tables.
- Not 'stumbling into' railings or tables while flying.
- You will not make footstep sounds while flying. The intention was to add a fluttering sound instead but I didn't get around to that.
- A weight-gate to flight (can't be too heavy to fly, but this was just an idea)

Here's a messy graph of my attempt at making nutrition cost dynamically calculated based on weight & nutrition (visible in linked PR) albeit probably flawed: https://www.desmos.com/calculator/ocle71zbpw
The plotted points are roughly aligned with the functions used to calculate cost. The intention was to have lighter flyers burn less nutrition, with heavier flyers burning more nutrition while getting heavier or lighter causes the cost to increase/decrease more severely the heavier or lighter you are.

**Comment by lbnesquik** [comment]
Honestly we could just smash the PR's together if that's the case.
Your PR has quite a bit more work in it really.
If anything, i just think the dynamic nutrition calculation is a bit messy and maybe calculation heavy. 

Also plz send me your discord for easier discussion

**Comment by lbnesquik** [comment]
I am in the process of smashing our PR's together with the exception of the weight - nutrition calculations for the moment. I'll just point out that you forgot a 'return' with the weight limit for taking off.

**Comment by lbnesquik** [comment]
Pushed the mix of features. Everything seems to work fine except for turfs and slowdown. It seems the player is still affected.

**Comment by lbnesquik** [comment]
Pushed wings sounds as well as a few other tooltips. Very descriptive i know.

**Comment by Vollybally** [comment]
Do you wish for me to merge this at this current point in time?

**Comment by Vollybally** [comment]
Actually nevermind I see you took dnm off. Merging it right now

**Comment by KasparoVy** [comment]
Brilliant that this got merged. If you don't mind, could you elaborate on what's up with turfs and slowdown @Ibnesquik? I can take a look through movement code and see what's good when I get some free time tonight

**Comment by lbnesquik** [comment]
@KasparoVy I did some quick testing and i didn't notice any difference in speed made by the implementation of this snipet.

https://github.com/KasparoVy/VOREStation/pull/1/files#diff-9b33d9e678eb2b8c3483848c518f68b2

**Comment by KasparoVy** [comment]
Sorry, what do you mean by speed? Performance impact or rate of nutrition depletion?

**Comment by lbnesquik** [comment]
The character had no change in movement speed between flying and non flying while traversing water or snow.

**Pull request merged**
