### PR TITLE
[DNM] [WIP] Supply Refactor

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Ports Polaris refactoring for the console to use NanoUI. 
For posterity, and as per recent practice, referring to the things I've ported over:
https://github.com/PolarisSS13/Polaris/pull/5432
https://github.com/PolarisSS13/Polaris/pull/5461
https://github.com/PolarisSS13/Polaris/pull/5505
https://github.com/PolarisSS13/Polaris/pull/5558

### CODE REVIEW

**Comment by Feasel** [comment]
Hopefully this is the right option... But it looks pretty good to me. Starting to catch up to some of the larger servers and their cargo, which are pretty fancy.

**Comment by Darlantanis** [comment]
Just tested this branch, here's my feedback.

Bugs: The "Space Parts and Space Vendors" PDA cartridge appears unable to display "Current Approved Orders" with either current orders or order history. "Current Requested Orders" still appears functional. 
Concerns: Public console allows anybody to view order history and export history. For Extended rounds, this introduces potential for metagaming/criticism from non-Cargo by providing information which is not their business. For antag rounds, public order history is particularly troubling for Cargo antags. I recommend removing these from the public console or restricting these features to those with Cargo access.

Summary of features
-New UI
-Addition of order history to cargo console
-Removal of "cancel shuttle" feature when ordering new crates
-Console lists crate contents while ordering
-Supply crates are now labelled with the "reason for request" provided during placing a request

**Comment by TheFurryFeline** [comment]
Hmm. I believe I could figure out how to restrict the history to
access_cargo, which would then leave it to be cargo viewing it, plus HOP
and CD. As for the PDA viewing issue, I'll also check up on that.

**Comment by Draycu** [comment]
Since there was a request to provide actual feedback from cargo players rather than just voting, I'll voice my concern and explain why I'm voting against merging this, for now.  In its current state, as you already know, TheFurryFeline, it would be open to abuse with public access to the new order history.  

If you can edit and make the changes you believe you can figure out with the PDA and unrestricted access to the order list, then it might not be a bad change overall and I would be happy with a merge.  I particularly enjoy the listing of a crate's contents which would be an appreciated change.

**Comment by AnonymousHybi** [comment]
Are you going to update this and continue to work on this or should I close it?

**Comment by TheFurryFeline** [comment]
Ehhh, there's only, eventually, to add the ability to cancel the initial call when away and to fix the PDA bug that got mentioned. Now there's also a map conflict so I'll close it for now and pick up on this again later.

**Pull request closed without merging**
