### PR TITLE
Fix for the Broken Jukeboxes.

### PR DESCRIPTION
**Pull request by Vulpias**
made a json file which should make the Jukeboxes useable. aka they don't runtime at the server start. 

found bugs -> jukeboxes don't produce sound.

Maybe the issue is the URL but I doubt that.

### CODE REVIEW

**Comment by ReddeyfishVor** [comment]
The reason no music plays is because your links don't lead to any actual files. They point to https://github.com/CHOMPstation/CHOMPstation/tree/master/sound/music

**Comment by Vulpias** [comment]
adding online urls to fix it

**Comment by ReddeyfishVor** [comment]
I'm not seeing the commit that changes them to online URLs. Are you sure you've pushed the commit to your fork?

**Comment by Arokha** [comment]
@ReddeyfishVor is correct, though I'd advise not committing your jukebox.json. We don't commit ours because it... well. Contains links to potentially illegal-to-share MP3s, and putting that on github is sharing access to copyrighted materials.

**Comment by ReddeyfishVor** [comment]
Going ahead and not commiting the jukebox.json. We have one working on our server now. Thank you for the insight, Arokha!

**Pull request closed without merging**
