### PR TITLE
Sprite Updates

### PR DESCRIPTION
**Pull request by IgiariValkyr**
Updates several sets of sprites to use TG art instead of the crappy Polaris art we've seen for the past like 5 years or longer.

Edits:
Closet.dmi (pseudo-front facing closets that aren't at this weird angle)
Computer.dmi (Four directional computers)
guncabinet.dmi (a nicer more secure looking cabinet)
tank.dmi (nicer looking air tanks with full air meters)
storage.dmi (nicer boxes and misc objects)

### CODE REVIEW

**Comment by AnonymousHybi** [comment]
Can you make sure that the fridge in the kitchen has its icon? When looking at closet.dmi I noticed the fridge icon has been deleted

**Comment by IgiariValkyr** [comment]
I remember doing it, so it should be in there. Let me look again.
---------------
Yeah there it is. Directly after the coffin but before the fire closet.

**Comment by Vollybally** [comment]
This seems to be an old pull request. Is it safe for me to merge it?

**Comment by Vollybally** [comment]
It passes all the checks so I'm assuming its safe to merge.

**Comment by IgiariValkyr** [comment]
Finally. *loud sigh emoji*

**Comment by Vollybally** [comment]
Sorry I jumped the gun and got told there was an issue in staff chat so like.. make another pull request aa. I'm new to this. I'll talk to jon tomorrow and make sure there isn't then I'll make the actual pull. Catto is a fool :notlikethis:
image

**Pull request merged**
